app/routes.py
# app/routes.py
from flask import Blueprint, render_template, request, redirect,abort, url_for, flash, session, g
import markdown
from app.services.user_service import UserService
from app.services.post_service import PostService
from app.services.comment_service import CommentService
from app.services.node_service import NodeService
from app.form import SiteForm, RegistrationForm, PostForm, CommentForm, confirmForm, SpaceForm, AdminUserForm, AdminNodeForm, AdminPostForm

main = Blueprint('main', __name__)


@main.app_template_filter('time_from_now')
def time_from_now(time):
    from datetime import datetime
    from babel.dates import format_timedelta
    return format_timedelta(datetime.now()-time, locale='zh_CN')

@main.app_template_filter('md_to_html')
def md_to_html(md):
    return markdown.markdown(md, extensions=['markdown.extensions.extra', 'markdown.extensions.codehilite','markdown.extensions.tables','markdown.extensions.toc'])

@main.route('/')
def index():
    n=NodeService.get_multi()
    nodes= {node.nid: (node.name, node.url) for node in n}
    pagination=PostService.get_multi_by_create(1)
    posts=pagination.items
    return render_template('index.html',title='首页',posts=posts,pagination=pagination,nodes=nodes)

@main.route('/page-<int:page>')
def index_page(page):
    n=NodeService.get_multi()
    pagination=PostService.get_multi_by_create(page)
    if page>pagination.pages:
        return index_page(pagination.pages)
    elif page<1:
        return index_page(1)
    posts=pagination.items
    nodes= {node.nid: (node.name, node.url) for node in n}
    return render_template('index.html',title='首页',posts=posts,pagination=pagination,nodes=nodes)

@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        usernameORemail = request.form['usernameORemail']
        if '@' in usernameORemail:
            user = UserService.get_by_email(usernameORemail)
        else:
            user = UserService.get_by_username(usernameORemail)
        password = request.form['password']
        if user and UserService.check_password(user.uid, password):
            session['user_id']=user.uid
            return redirect(url_for('main.index'))
        else:
            flash('用户名或邮箱或密码错误', 'error')
    return render_template('login.html', title='登录')

@main.route('/logout')
def logout():
    session['user_id']=None
    return redirect(url_for('main.index'))

@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        UserService.add_user(form.username.data, form.password.data, form.email.data, 2, 1)
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='注册',form=form)

@main.route('/space/<int:uid>')
def space(uid):
    space=UserService.get_one(uid)
    if not space:
        return render_template('404.html', title='404')
    return render_template('space.html', title='个人空间', space=space)

@main.route('/space/<int:uid>/setting', methods=['GET', 'POST'])
def space_setting(uid):
    if g.user.uid != uid or g.user.check_ban_status('BANNED_SETTING'):
        return render_template('401.html', title='无权访问')
    user=UserService.get_one(uid)
    form=SpaceForm(obj=user)
    if request.method == 'POST':
        if form.validate_on_submit():
            UserService.update_profile(uid, form.avatar.data, form.bio.data)
            return redirect(url_for('main.space', uid=uid))
    return render_template('space_setting.html', title='设置', form=form)

@main.route('/post/<int:pid>', methods=['GET', 'POST'])
def post_detial(pid):
    post = PostService.get_one(pid)
    node = NodeService.get_one(post.node)
    if g.user.level < post.access_level or g.user.check_ban_status('BANNED_ALL'):
        return render_template('401.html', title='无权访问')
    form= CommentForm()
    if g.user.uid != None:
        PostService.add_views(pid)
    comments=CommentService.get_comments(pid)
    title = post.title
    if request.method == 'POST':
        if form.validate_on_submit():
            CommentService.add_comment( form.content.data, g.user.uid, pid)
            return redirect(url_for('main.post_detial', pid=pid))
    return render_template('post_detail.html', title=title, post=post, comments=comments, node=node, form=form)

@main.route('/post/create', methods=['GET', 'POST'])
def post_create():
    if not g.user.has_priv('PRIV_USER') or g.user.check_ban_status('BANNED_POST'):
        return redirect(url_for('main.login'))
    form = PostForm()
    nodes=NodeService.get_multi()
    form.node.choices = [(n.nid, n.name) for n in nodes]
    if form.validate_on_submit():
        user_id = g.user.uid
        post=PostService.add_post(form.title.data, form.content.data, user_id, form.node.data)
        return redirect(url_for('main.post_detial', pid=post.pid))
    return render_template('post_create.html', title='创建讨论', form=form)


@main.route('/post/<int:pid>/edit', methods=['GET', 'POST'])
def post_edit(pid):
    post=PostService.get_one(pid)
    if g.user.uid != post.author and not g.user.has_priv('PRIV_ADMIN') and g.user.check_ban_status('BANNED_POST'):
        return render_template('401.html', title='无权访问')
    form = PostForm(obj=post)
    nodes=NodeService.get_multi()
    form.node.choices = [(n.nid, n.name) for n in nodes]
    if request.method == 'POST':
        if form.validate_on_submit():
            PostService.update_post(pid, form.title.data, form.content.data, form.node.data)
            return redirect(url_for('main.post_detial', pid=pid))
    return render_template('post_edit.html', title='编辑主题', form=form,post=post)

@main.route('/post/<int:pid>/delete', methods=['GET', 'POST'])
def post_delete(pid):
    post=PostService.get_one(pid)
    if not g.user.has_priv('PRIV_ADMIN'):
        return render_template('401.html', title='无权访问')
    form=confirmForm()
    if form.validate_on_submit() and request.method == 'POST':
        print('delete post')
        PostService.delete_post(pid)
        return redirect(url_for('main.index'))
    message='您正在删除主题：「'+post.title+'」，请做最后确认！'
    return render_template('action_confirm.html', title='操作确认',message=message,action='/post/'+str(pid)+'/delete',form=form)

@main.route('/comment/<int:cid>/edit', methods=['GET', 'POST'])
def comment_edit(cid):
    comment=CommentService.get_comment(cid)
    if g.user.uid != comment.author or not g.user.has_priv('PRIV_ADMIN') or g.user.check_ban_status('BANNED_COMMENT'):
        return render_template('401.html', title='无权访问')
    form = CommentForm(obj=comment)
    if request.method == 'POST':
        if form.validate_on_submit():
            CommentService.update_comment(cid, form.content.data)
            return redirect(url_for('main.post_detial', pid=comment.post))
    return render_template('comment_edit.html', title='编辑评论', form=form,comment=comment)

@main.route('/node')
def node():
    nodes=NodeService.get_multi()
    return render_template('node.html', title='节点',nodes=nodes)

@main.route('/node/<string:url>')
def node_detail(url):
    node=NodeService.get_by_url(url)
    pagination=PostService.get_multi_by_create(1,node.nid)
    posts=pagination.items
    return render_template('node_detail.html', title=node.name, node=node, posts=posts,pagination=pagination)

@main.route('/node/<string:url>/page-<int:page>')
def node_detail_page(url,page):
    node=NodeService.get_by_url(url)
    pagination=PostService.get_multi_by_create(page,node.nid)
    if page>pagination.pages:
        return index_page(pagination.pages)
    elif page<1:
        return index_page(1)
    posts=pagination.items
    return render_template('node_detail.html', title=node.name, node=node, posts=posts,pagination=pagination)
@main.route('/admin',methods=['GET', 'POST'])
def admin():
    if not g.user.has_priv('PRIV_ADMIN'):
        return render_template('401.html', title='无权访问')
    userform = AdminUserForm()
    nodeform = AdminNodeForm()
    postform = AdminPostForm()
    if request.method == 'POST':
        if userform.submit.data and userform.validate_on_submit():
            uids=userform.uid.data.split(' ')
            dic={}
            if userform.level.data!=None:
                dic['level']=userform.level.data
            if userform.priv.data!=None:
                dic['priv']=userform.priv.data
            if userform.banned_status.data!=None:
                dic['banned']=userform.banned_status.data
            for uid in uids:
                if not UserService.get_one(uid):
                    flash('UID'+uid+'不存在', 'user')
                    return redirect(url_for('main.admin')+'#user_control')
                UserService.update_user(uid=uid, **dic)
            flash('提交成功', 'user')
            return redirect(url_for('main.admin')+'#user_control')
        if postform.submit.data and postform.validate_on_submit():
            pids=postform.pid.data.split(' ')
            dic={}
            if postform.node.data!=None:
                if not NodeService.get_one(postform.node.data):
                    flash('NID'+str(postform.node.data)+'不存在', 'post')
                    return redirect(url_for('main.admin')+'#post_control')
                dic['node']=postform.node.data
            if postform.access_level.data!=None:
                dic['access_level']=postform.access_level.data
            if postform.sort.data!=None:
                dic['sort']=postform.sort.data
            dic['topped']=postform.topped.data
            dic['readonly']=postform.readonly.data
            for pid in pids:
                if not PostService.get_one(pid):
                    flash('PID'+pid+'不存在', 'post')
                    return redirect(url_for('main.admin')+'#post_control')
                PostService.update_by_admin(pid=pid, **dic)
            flash('提交成功', 'post')

app/templates/401.html
{% extends "base.html" %}

{% block content %}
<h1 style="text-align:center;">Access Denied!</h1>
{% endblock %}

app/templates/action_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="content">
    <div id="main-full">
        <div class="box">
            <div style="display: flex;justify-content: center;">
                <div class="cell" style="flex-direction: column;width:100%;">
                    <h1 style="text-align:center;">{{ title }}</h1>
                    <p>{{ message }}</p>
                </div>
            </div>
            <div class="sep10"></div>
            <li class="cell" style="justify-content: center;">
                <form action="{{ action }}" method="post" style="display: inline-block;">
                    {{ form.hidden_tag() }}
                    <input type="submit" value="Yes" style="margin-right:50px">
                    <button type="button" class = "btn-normal" onclick="window.history.back()">No</button>
                    <div class="sep10"></div>
                </form>
            </li>
            <div class="sep10"></div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/admin.html
{% extends "base.html" %}

{% block content %}
<div class="content">
    <div class="box">
        <div class="cell flex-one-row">
            <h1>管理后台</h1>
        </div>
        <div class="sep20"></div>
        <div id="user_control" class="cell" style="display:flex;flex-direction:column;">
            <h3>用户管理</h3>
            <form action="/admin" method="post">
                {{userform.hidden_tag()}}
                <label for="uid">Uid（多个以空格分隔，必填）：</label>
                <div class="sep10"></div>
                {{userform.uid(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                <label for="level">等级(0-5)：</label>
                <div class="sep10"></div>
                {{userform.level(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                <label for="privilege">权限(1-3)：</label>
                <div class="sep10"></div>
                {{userform.priv(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                <label for="ban">封禁状态(0-5)：</label>
                <div class="sep10"></div>
                {{userform.banned_status(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages and messages[0][0]=='user' %}
                    <ul>
                        {% for category, message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% endwith %}
                {{userform.submit(class="btn",style="width:20%",value="提交")}}
                <div class="sep20"></div>
            </form>
        </div>
        <div class="sep20"></div>
        <div id="post_control" class="cell" style="display:flex;flex-direction:column;">
            <h3>主题管理</h3>
            <form action="/admin" method="post">
                {{postform.hidden_tag()}}
                <label for="pid">Pid（多个以空格分隔，必填）：</label>
                <div class="sep10"></div>
                {{postform.pid(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                <label for="node">隶属节点Nid：</label>
                <div class="sep10"></div>
                {{postform.node(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>    
                <label for="access_level">阅读等级(0-5)：</label>
                <div class="sep10"></div>
                {{postform.access_level(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                <label for="sort">排序优先级(越大越靠前)：</label>
                <div class="sep10"></div>
                {{postform.sort(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                <label for="is_top">置顶：{{postform.topped}}</label>
                <div class="sep10"></div>
                <label for="readonly">只读：{{postform.readonly}}</label>
                <div class="sep10"></div>
                {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages and messages[0][0]=='post'%}
                    <ul>
                        {% for category, message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% endwith %}
                {{postform.submit(class="btn",style="width:20%",value="提交")}} 
                <div class="sep20"></div>
            </form>
        </div>
        <div class="sep20"></div>
        <div id="node_control" class="cell" style="display:flex;flex-direction:column;">
            <h3>节点管理</h3>
            <form action="/admin" method="post">
                {{nodeform.hidden_tag()}}
                <label for="nid">Nid（不支持批量更改，留空视为新建）：</label>
                <div class="sep10"></div>
                {{nodeform.nid(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                <label for="name">节点名：</label>
                <div class="sep10"></div>
                {{nodeform.name(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                <label for="description">描述：</label>
                <div class="sep10"></div>
                {{nodeform.description(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                <label for="url">链接：</label>
                <div class="sep10"></div>
                {{nodeform.url(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                <label for="avatar">图标：</label>
                <div class="sep10"></div>
                {{nodeform.avatar(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                <label for="access_level">阅读等级(0-5)：</label>
                <div class="sep10"></div>
                {{nodeform.access_level(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                <label for="parent">父节点Nid(大于等于1，1为无父节点)：</label>
                <div class="sep10"></div>
                {{nodeform.parent(class="input-normal",style="width:60%")}}
                <div class="sep10"></div>
                {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages and messages[0][0]=='node'%}
                    <ul>
                        {% for category, message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% endwith %}
                {{nodeform.submit(class="btn",style="width:20%",value="提交")}}
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/comment.html
<div id="back">
<span>评论</span>
<form method="post" action={{ url_for('main.post_detial',pid=post.pid)}}>
    {{ form.hidden_tag() }}
    {{form.cid(type="hidden")}}
    <div class="sep10"></div>
    <div class="cell">
        {{ form.content(style="", maxlength="20000", id="editor" ,placeholder="请输入评论，支持Markdown语法") }}
    </div>
    <div style="padding: 10px; padding-left: 0;">
        <input type="submit" value="编辑/发布评论" >
    </div>
</form>
</div>

app/templates/comment_edit.html
<!-- templates/new_post.html -->

{% extends "base.html" %}
{% block content %}
<div class="content">
    <div id="leftbar"></div>
    <div id="rightbar">
        <div class="sep20"></div>
        <div class="box">
            <h1>发帖提示</h1>
        </div>
        <div class="sep20"></div>
    </div>
    <div id="main">
        <div class="sep20"></div>
        <div class="box">
            <div class="cell flex-one-row">
                <h2>编辑评论</span>
            </div>
            <form method="post" action={{ url_for('main.comment_edit',cid=comment.cid)}}>
                {{ form.hidden_tag() }}
                <div class="sep20"></div>
                <label for="content">正文:</label>
                <div class="sep10"></div>
                <div class="cell">
                    {{ form.content(maxlength="20000", id="editor" ,placeholder="请输入主题正文，支持Markdown语法") }}
                </div>
                <div class="sep20"></div>
                <label for="preview">预览:</label>
                <div class="sep10"></div>
                <div class="cell">
                    <div id="preview">
                        <div id="markdown-preview"><p style="color:#556;">请输入主题正文，此处为预览</p></div>
                    </div>
                </div>
                <div class="sep20"></div>
                <div class="cell"  style="padding: 10px; padding-left: 0;">
                    <input type="submit" value="编辑讨论" >
                </div>
            </form>
        </div>
        <div class="sep20"></div>
    </div>
</div>
<script src="{{ url_for('static', filename='js/md-preview.js') }}"></script>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="content">
    <div id="Leftbar"></div>
    <div id="rightbar">
        {% include 'rightbar_user.html' %}
    </div>  
    <div id="main">
        <div class="box">
            {% if not posts %}
            <div class="inner">
                <h3 style="text-align:center;">暂无内容</p>
            </div>
            {% else %}
                {% for post in posts %}
                <div class="cell item" id="post{{post.pid}}">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tbody>
                            <tr>
                                <td width="48" valign="top" align="center">
                                    <a href="/space/{{ post.author }}"target="blank">
                                        <img src="{{ post.avatar}}" class="avatar" border="0" align="default" width="48" style="width: 48px; max-height: 48px;" >
                                    </a>
                                </td>
                                <td width="10"></td>
                                <td width="auto" valign="middle">
                                    <span class="item_title">
                                        <a href="/post/{{ post.pid }}" class="topic-link">{{ post.title }}</a>
                                    </span>
                                    <div class="sep5"></div>
                                    <span class="topic_info">
                                        <strong><a href="/space/{{ post.author }}" target="blank">{{ post.username }}</a></strong>
                                        &nbsp;•&nbsp;
                                        <strong>{{ post.created_at | time_from_now }}前</strong>
                                        &nbsp;•&nbsp;
                                        <strong>{{ post.views }} 点击</strong>
                                    </span>
                                </td>
                                <td width="70" valign="middle">
                                    <a href="/node/{{nodes[post.node][1]}}" class="node-item node-use">{{nodes[post.node][0]}}</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="sep10"></div>
                {% endfor %}
                <div class="cell ps_container">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tbody>
                            <tr>
                                <td width="80%" align="left">
                                    {% if pagination.it_pages %}
                                        {% for p in range(1, pagination.it_pages + 1)%}
                                        {% if p == pagination.page %}
                                            <a href="{{ url_for('main.index_page', page=p) }}" class="page_current">{{ p }}</a>
                                            &nbsp;
                                        {% else %}
                                            <a href="{{ url_for('main.index_page', page=p) }}" class="page_normal">{{ p }}</a>
                                            &nbsp;
                                        {% endif %}
                                        {% endfor %}
                                        <span style="color:#ccc;">......</span>
                                        {% if pagination.page == pagination.pages %}
                                        <a href="{{ url_for('main.index_page', page=pagination.pages) }}" class="page_current">{{ pagination.pages }}</a>
                                        &nbsp;
                                        {% else %}
                                        <a href="{{ url_for('main.index_page', page=pagination.pages) }}" class="page_normal">{{ pagination.pages }}</a>
                                        &nbsp;
                                        {% endif %}
                                    {% else %}
                                        {% for p in range(1, pagination.pages + 1)%}
                                        {% if p == pagination.page %}
                                            <a href="{{ url_for('main.index_page', page=p) }}" class="page_current">{{ p }}</a>
                                            &nbsp;
                                        {% else %}
                                            <a href="{{ url_for('main.index_page', page=p) }}" class="page_normal">{{ p }}</a>
                                            &nbsp;
                                        {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                </td>
                                <td width="20%" align="right">
                                    {% if pagination.has_prev %}
                                    <a href="{{ url_for('main.index_page', page=pagination.prev_num) }}">上一页</a>
                                    {% endif %}
                                    {% if pagination.has_next %}
                                    <a href="{{ url_for('main.index_page', page=pagination.next_num) }}">下一页</a>
                                    {% endif %}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

app/templates/install.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ title }}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/code.css') }}">
    <script src="{{ url_for('static', filename='js/markdown-it.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    {% block extra_head %}{% endblock %}
</head>
<body>
    <div id="Wrapper">
        <div class="sep20"></div>
        <div class="content">
            <div id = "main-full">
                <div class="box">
                    <div>
                        <h2>安装</h2>
                    </div>
                    <div class="inner">
                        <p>欢迎使用本程序，请按照以下步骤进行安装：</p>
                        <ol>
                            <li>创建数据库</li>
                            <li>修改配置文件</li>
                            <li>初始化数据库</li>
                            <li>创建管理员账号</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="sep20"></div>
    </div>
</body>
</html>

app/templates/post_create.html
<!-- templates/new_post.html -->

{% extends "base.html" %}
{% block content %}
<div class="content">
    <div id="leftbar"></div>
    <div id="rightbar">
        <div class="sep20"></div>
        <div class="box">
            <h1>发帖提示</h1>
        </div>
        <div class="sep20"></div>
    </div>
    <div id="main">
        <div class="sep20"></div>
        <div class="box">
            <div class="cell flex-one-row">
                <h2>发表新主题</span>
            </div>
            <form method="post" action={{ url_for('main.post_create')}}>
                {{ form.hidden_tag() }}
                <div class="cell">
                    {{ form.title(class_="new-title-input", tabindex="1", rows="1", maxlength="120", id="topic_title", autofocus=True, placeholder="请输入主题标题，以简要表达内容", style="font-size: 16px; line-height: 100%; overflow: hidden; overflow-wrap: break-word; height: 36px;") }}
                </div>
                <div class="sep20"></div>
                <label for="content">正文:</label>
                <div class="sep10"></div>
                <div class="cell">
                    {{ form.content(maxlength="20000", id="editor" ,placeholder="请输入主题正文，支持Markdown语法") }}
                </div>
                <div class="sep20"></div>
                <label for="preview">预览:</label>
                <div class="sep10"></div>
                <div class="cell">
                    <div id="preview">
                        <div id="markdown-preview"><p style="color:#556;">请输入主题正文，此处为预览</p></div>
                    </div>
                </div>
                <div class="sep20"></div>
                <div style="display:flex;flex-direction:row;align-items: center;">
                    <label style="width:8%;font-size:20px"for="node">节点:</label>
                    <div style="border-bottom:none;">
                        {{ form.node(maxlength="120", id="node-select") }}
                    </div>
                </div>
                <div class="sep20"></div>
                <div class="cell"  style="padding: 10px; padding-left: 0;">
                    <input type="submit" value="发布主题" >
                </div>
            </form>
        </div>
        <div class="sep20"></div>
    </div>
</div>
<script src="{{ url_for('static', filename='js/md-preview.js') }}"></script>
{% endblock %}

app/templates/register.html
<!-- templates/register.html -->

{% extends "base.html" %}

{% block content %}
<div class="login-container">
    <h2>注册</h2>
    <form method="POST" action="{{ url_for('main.register') }}">
            {{ form.hidden_tag() }}
            <label for="username">用户名:</label>
            {{ form.username }}
            {% for error in form.username.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}
            <label for="email">邮箱:</label>

            {{ form.email }}
            {% for error in form.email.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}

            <label for="password">密码:</label>
            {{ form.password}}
            {% for error in form.password.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}

            <label for="confirm_password">重复密码:</label>
            {{ form.confirm_password }}
            {% for error in form.confirm_password.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}
            {{ form.submit() }}
    </form>
</div>
{% endblock %}

app/templates/rightbar_user.html
<div class="box">
        {% if g.user.has_priv('PRIV_USER') %}
        <div class="cell">
            <img src="{{ g.user.avatar }}" id="avatar">
            <a href="/space/{{ g.user.uid }}" class="top" style="font-size:25px; padding:10px; align-items: center;">{{ g.user.username }}</a>
        </div>
        <div class="sep20"></div>
        {% if not g.user.check_ban_status('BANNED_POST')%}
            <div class="btn normal">
                <a href="{{ url_for('main.post_create') }}">发表新主题</a>
            </div>
        {% endif %}
        {% else %}
        <div class="cell">
            <p>朋友你好，看起来你是新来的！如果需要参与讨论，请：<p>
        </div>
        <a href="/login" class="top" style="font-size:25px; padding-right: 15px; align-items: center;" >登录</a>
        <a href="/register" class="top" style="font-size:25px; align-items: center;" >注册</a>
        {% endif %}
</div>

app/templates/space_setting.html
{% extends "base.html" %}

{% block content %}
<div class="content">
    <div id="main-full">
        <div class="box">
            <div class="flex-one-row">
                <h1>空间设置</h1>
            </div>
            <form method="post" action={{ url_for('main.space_setting',uid=g.user.uid) }}>
                {{ form.hidden_tag() }}
                <label for="bio">个人简介:</label>
                <div class="sep10"></div>
                {{ form.bio(style="width:80%", maxlength="200", id="editor" ,placeholder="请输入个人简介，支持Markdown语法") }}
                <div class="sep20"></div>
                <label for="avatar">头像URL:</label>
                <div class="sep10"></div>
                {{ form.avatar(style="", id="node-select") }}
                <div class="sep20"></div>
                <input type="submit" value="更新空间设置" style="" >
            </form>
        </div>
    </div>
</div>
{% endblock %}